module.exports = {
    GOLOS_NODE: 'wss://apibeta.golos.today/ws',
    //GOLOS_CHAIN_ID: '5876894a41e6361bde2e73278f07340f2eb8b41c2facd29099de9deef6cdb679',
    REST_API: 'http://37.18.27.45:5000',
    FORUM: {
        _id: 'golostalks',
        creator: 'cyberfounder',
        // html is supported in all fields excl. breadcrumb_title, page_title
        ru: {
            title: 'Форум на Голосе',
            description: 'На этом форуме <b>каждый</b> может что-нибудь написать, да еще и получить донаты :)',
            breadcrumb_title: 'GolosTalks',
            logo_title: 'GolosTalks.com',
            page_title: 'Форум на ГОЛОС',
            footer_title: 'GolosTalks.com',
            footer_description: 'Экспериментальный форум, построенный на основе <a href="https://golos.id" target="_new">блокчейна Голос</a>.<br/>Разработан <a href="https://golos.id/@id-raccoon-hater" target="_new">id-raccoon-hater</a>.'
        },
        en: {
            title: 'Forum on Golos Blockchain',
            description: 'On this forum <b>you</b> can post, donate and receive others donates :)',
            breadcrumb_title: 'GolosTalks',
            logo_title: 'GolosTalks.com',
            page_title: 'Forum on GOLOS',
            footer_title: 'GolosTalks.com',
            footer_description: 'An experimental forum built on top of the <a href="https://golos.id" target="_new">Golos Blockchain</a>.<br/>Brought to you by <a href="https://golos.id/@id-raccoon-hater" target="_new">id-raccoon-hater</a>.'
        }
    },
    STM_Config: {
        img_proxy_prefix: 'https://steemitimages.com/',
        ipfs_prefix: false,
        upload_image: 'https://steemitimages.com',
    },
    PROGRESSION: {
        increment: 25,
        steps: [
            1.375, 4.050, 7.959, 14.300,
            23.587, 35.625, 50.225, 67.200,
            86.362, 107.525, 130.500, 155.100,
            178.450, 200.550
        ]
    },
    BOTS: [
        'adsactly',
        'analisa',
        'animus',
        'appreciator',
        'arama',
        'ausbitbot',
        'bago',
        'banjo',
        'barrie',
        'bellyrub',
        'besttocome215',
        'bierkaart',
        'biskopakon',
        'bitgeek',
        'blackwidow7',
        'blimbossem',
        'boomerang',
        'booster',
        'boostupvote',
        'bot-helper',
        'bottymcbotface',
        'bowlofbitcoin',
        'bp423',
        'buildawhale',
        'burdok213',
        'businessbot',
        'calva',
        'cannabiscurator',
        'centerlink',
        'cleverbot',
        'cnbuddy',
        'counterbot',
        'cryptoowl',
        'cub1',
        'curationrus',
        'dab4dab',
        'dahrma',
        'davidding',
        'decibel',
        'deutschbot',
        'dirty.hera',
        'discordia',
        'done',
        'drakkald',
        'drotto',
        'edrivegom',
        'emilhoch',
        'eoscrusher',
        'famunger',
        'feedyourminnows',
        'followforupvotes',
        'frontrunner',
        'funaddaa',
        'fuzzyvest',
        'gaman',
        'gamerpool',
        'gamerveda',
        'gaming-hangouts',
        'gindor',
        'givemedatsteem',
        'givemesteem1',
        'glitterbooster',
        'gonewhaling',
        'goodbot',
        'gotvotes',
        'gpgiveaways',
        'heelpopulair',
        'helpfulcrypto',
        'idioticbot',
        'ikwindje',
        'ilvacca',
        'inchonbitcoin',
        'ionlysaymeep',
        'ipuffyou',
        'joanaltres',
        'libertyteeth',
        'lovejuice',
        'mahabrahma',
        'make-a-whale',
        'makindatsteem',
        'maradaratar',
        'minnowbooster',
        'minnowhelper',
        'minnowpond',
        'minnowpond1',
        'minnowpondblue',
        'minnowpondred',
        'minnowsupport',
        'misterwister',
        'moisesmcardona',
        'moonbot',
        'morwhale',
        'moses153',
        'msp-lovebot',
        'msp-shanehug',
        'musicbooster',
        'muxxybo',
        'myday',
        'ninja-whale',
        'ninjawhale',
        'officialfuzzy',
        'onlymanamana',
        'originalwork',
        'originalworks',
        'pharesim',
        'pimpoesala',
        'polsza',
        'portoriko',
        'prambarbara',
        'promoted',
        'pumpingbitcoin',
        'pushup',
        'qurator',
        'qwasert',
        'raidrunner',
        'ramta',
        'randovote',
        'randowhale',
        'randowhale0',
        'randowhale1',
        'randowhaletrail',
        'randowhaling',
        'reblogger',
        'resteem.bot',
        'resteemable',
        'resteembot',
        'russiann',
        'scamnotifier',
        'scharmebran',
        'screenname',
        'siliwilly',
        'sneaky-ninja',
        'sniffo35',
        'spinbot',
        'stackin',
        'statsmonkey',
        'steem-untalented',
        'steemcleaners',
        'steemedia',
        'steemgigs',
        'steemholder',
        'steemit-gamble',
        'steemit-hangouts',
        'steemitboard',
        'steemmaker',
        'steemmemes',
        'steemminers',
        'steemode',
        'steemprentice',
        'steemsquad',
        'steemster3',
        'steemthat',
        'steemvoter',
        'stephen.king989',
        'tabea',
        'tarmaland',
        'thepunisher',
        'theupvoter',
        'timbalabuch',
        'tippy',
        'tipu',
        'treeplanter',
        'twitterbot',
        'utopian-io',
        'viraltrend',
        'votey',
        'waardanook',
        'wahyurahadiann',
        'wang',
        'weareone1',
        'weenis',
        'welcomebot',
        'whatamidoing',
        'whatupgg',
        'wildoekwind',
        'wiseguyhuh',
        'wistoepon',
        'zdashmash'
    ]
};
