version: "3"
services:

    ui-forums:
        image: golosblockchain/forum-ui:latest
        build: .
        restart: always
        volumes:
            - ./config/default.js:/var/app/config/default.js
            - ./public/custom.css:/var/app/public/custom.css
        ports:
            - "3000:3000"
