version: "3"
services:

    ui-forums:
        image: golosblockchain/forum-ui:latest
        build: .
        restart: always
        volumes:
            - ./config/default.js:/config/default.js
        ports:
            - "3000:3000"
