version: "3"
services:

    chainbb:
        image: golosblockchain/forum-ui:latest
        build: .
        restart: always
        depends_on:
            - chainbb-rest
        volumes:
            - ./config.js:/config.js
            - ./configSecure.js:/configSecure.js
        ports:
            - "3000:3000"

    chainbb-rest:
        image: golosblockchain/forum-ui:rest
        build:
            context: .
            dockerfile: server/Dockerfile
        restart: always
        volumes:
            - ./config.js:/config.js
            - ./configSecure.js:/configSecure.js
        ports:
            - "5000:5000"
