// Account
export const ACCOUNT_FETCH = 'ACCOUNT_FETCH';
export const ACCOUNT_NOTIFICATIONS_FETCH = 'ACCOUNT_NOTIFICATIONS_FETCH';
export const ACCOUNT_FOLLOWING_APPEND = 'ACCOUNT_FOLLOWING_APPEND';
export const ACCOUNT_FOLLOWING_REMOVE = 'ACCOUNT_FOLLOWING_REMOVE';

export const ACCOUNT_SIGNIN = 'ACCOUNT_SIGNIN';
export const ACCOUNT_SIGNOUT = 'ACCOUNT_SIGNOUT';
export const ACCOUNT_STATE_RESOLVED = 'ACCOUNT_STATE_RESOLVED';

export const ACCOUNTS_ADD = 'ACCOUNTS_ADD';
export const ACCOUNTS_REMOVE = 'ACCOUNTS_REMOVE';
export const ACCOUNTS_REMOVE_ALL = 'ACCOUNTS_REMOVE_ALL';

// State of entities loaded from the blockchain
export const CHAINSTATE_ACCOUNT_LOAD_FAILED = 'CHAINSTATE_ACCOUNT_LOAD_FAILED';
export const CHAINSTATE_ACCOUNT_LOAD_PROCESSING = 'CHAINSTATE_ACCOUNT_LOAD_PROCESSING';
export const CHAINSTATE_ACCOUNT_LOAD_RESOLVED = 'CHAINSTATE_ACCOUNT_LOAD_RESOLVED';
export const CHAINSTATE_GLOBAL_PROPS_RESOLVED = 'CHAINSTATE_GLOBAL_PROPS_RESOLVED';
export const CHAINSTATE_STATE_RESOLVED = 'CHAINSTATE_STATE_RESOLVED';

// Breadcrumb
export const SET_BREADCRUMB = 'SET_BREADCRUMB';

// Forum
export const FORUM_LOAD_RESOLVED = 'FORUM_LOAD_RESOLVED';
export const FORUM_SUBSCRIBE = 'FORUM_SUBSCRIBE';
export const FORUM_UNSUBSCRIBE = 'FORUM_UNSUBSCRIBE';

// Forum - Configuration
export const FORUM_CONFIG_PROCESSING = 'FORUM_CONFIG_PROCESSING';
export const FORUM_CONFIG_RESOLVED = 'FORUM_CONFIG_RESOLVED';
export const FORUM_CONFIG_RESOLVED_ERROR = 'FORUM_CONFIG_RESOLVED_ERROR';

// Forum - Reservation
export const FORUM_RESERVATION_PROCESSING = 'FORUM_RESERVATION_PROCESSING';
export const FORUM_RESERVATION_RESOLVED = 'FORUM_RESERVATION_RESOLVED';
export const FORUM_RESERVATION_RESOLVED_ERROR = 'FORUM_RESERVATION_RESOLVED_ERROR';

// Moderation
export const MODERATION_HIDE_PROCESSING = 'MODERATION_HIDE_PROCESSING';
export const MODERATION_HIDE_RESOLVED = 'MODERATION_HIDE_RESOLVED';
export const MODERATION_HIDE_RESOLVED_ERROR = 'MODERATION_HIDE_RESOLVED_ERROR';
export const MODERATION_REVEAL_PROCESSING = 'MODERATION_REVEAL_PROCESSING';
export const MODERATION_REVEAL_RESOLVED = 'MODERATION_REVEAL_RESOLVED';
export const MODERATION_REVEAL_RESOLVED_ERROR = 'MODERATION_REVEAL_RESOLVED_ERROR';

export const MODERATION_BAN_PROCESSING = 'MODERATION_BAN_PROCESSING';
export const MODERATION_BAN_RESOLVED = 'MODERATION_BAN_RESOLVED';
export const MODERATION_BAN_RESOLVED_ERROR = 'MODERATION_BAN_RESOLVED_ERROR';
export const MODERATION_UNBAN_PROCESSING = 'MODERATION_UNBAN_PROCESSING';
export const MODERATION_UNBAN_RESOLVED = 'MODERATION_UNBAN_RESOLVED';
export const MODERATION_UNBAN_RESOLVED_ERROR = 'MODERATION_UNBAN_RESOLVED_ERROR';

// Private Messages
export const MESSAGES_SEARCH = 'MESSAGES_SEARCH';
export const MESSAGES_SEARCH_RESOLVED = 'MESSAGES_SEARCH_RESOLVED';
export const MESSAGES_SEND = 'MESSAGES_SEND';
export const MESSAGES_ADD_RESOLVED = 'MESSAGES_ADD_RESOLVED';
export const MESSAGES_LOAD = 'MESSAGES_LOAD';
export const MESSAGES_LOAD_RESOLVED = 'MESSAGES_LOAD_RESOLVED';
export const MESSAGES_MESSAGED = 'MESSAGES_MESSAGED';
export const MESSAGES_EDITED = 'MESSAGES_EDITED';
export const MESSAGES_READ = 'MESSAGES_READ';
export const MESSAGES_DELETED = 'MESSAGES_DELETED';

export const MESSAGES_CONTACTS_LOAD = 'MESSAGES_CONTACTS_LOAD';
export const MESSAGES_CONTACTS_LOAD_RESOLVED = 'MESSAGES_CONTACTS_LOAD_RESOLVED';

// Post
export const POST_VOTE = 'POST_VOTE';
export const POST_VOTE_PROCESSING = 'POST_VOTE_PROCESSING';
export const POST_VOTE_RESOLVED = 'POST_VOTE_RESOLVED';
export const POST_VOTE_RESOLVED_ERROR = 'POST_VOTE_RESOLVED_ERROR';
export const POST_VOTE_RESOLVED_ERROR_CLEAR = 'POST_VOTE_RESOLVED_ERROR_CLEAR';

export const POST_DONATE_PROCESSING = 'POST_DONATE_PROCESSING';
export const POST_DONATE_RESOLVED = 'POST_DONATE_RESOLVED';
export const POST_DONATE_RESOLVED_ERROR = 'POST_DONATE_RESOLVED_ERROR';
export const POST_DONATE_RESOLVED_ERROR_CLEAR = 'POST_DONATE_RESOLVED_ERROR_CLEAR';
;
export const POST_SUBMIT_ERROR = 'POST_SUBMIT_ERROR';
export const POST_SUBMIT_RESOLVED = 'POST_SUBMIT_RESOLVED';

export const POST_LOAD = 'POST_LOAD'
export const POST_LOAD_BY_AUTHOR_RESOLVED = 'POST_LOAD_BY_AUTHOR_RESOLVED';
export const POST_LOAD_LIVE_RESOLVED = 'POST_LOAD_LIVE_RESOLVED';
export const POST_LOAD_REPLIES_BY_AUTHOR_RESOLVED = 'POST_LOAD_REPLIES_BY_AUTHOR_RESOLVED';
export const POST_LOAD_REPLIES_BY_AUTHOR_STARTED = 'POST_LOAD_REPLIES_BY_AUTHOR_STARTED';
export const POST_LOAD_RESOLVED = 'POST_LOAD_RESOLVED';
export const POST_LOAD_RESPONSES = 'POST_LOAD_RESPONSES';
export const POST_LOAD_RESPONSES_BY_AUTHOR_RESOLVED = 'POST_LOAD_RESPONSES_BY_AUTHOR_RESOLVED';
export const POST_LOAD_RESPONSES_RESOLVED = 'POST_LOAD_RESPONSES_RESOLVED';
export const POST_LOAD_VOTES_RESOLVED = 'POST_LOAD_VOTES_RESOLVED';

export const POST_LOAD_DONATES_RESOLVED = 'POST_LOAD_DONATES_RESOLVED';
export const POST_LOAD_DONATES_BY_AUTHOR_RESOLVED = 'POST_LOAD_DONATES_BY_AUTHOR_RESOLVED';

export const POST_RESET_STATE = 'POST_RESET_STATE';
export const POST_REMOVE_LIVE = 'POST_REMOVE_LIVE';

// Preferences
export const SET_PREFERENCE = 'SET_PREFERENCE';

// search
export const SEARCH = 'SEARCH';
export const SEARCH_RESOLVED = 'SEARCH_RESOLVED';

// status
export const SET_STATUS = 'SET_STATUS';
